const svgOptions = {
  plugins: [
    { cleanupAttrs: true },
    { mergePaths: true },
    { removeAttrs: { attrs: '(stroke|fill)' } },
    { removeDimensions: true },
    { removeDoctype: true },
    { removeNonInheritableGroupAttrs: true },
    { removeStyleElement: true },
    { removeTitle: true },
    { removeUselessDefs: true },
    { removeUselessDefs: true },
    //
    { cleanupAttrs: true },
    { cleanUpEnableBackground: true },
    { cleanupIDs: true },
    { cleanupNumericValues: true },
    { collapseGroups: true },
    { convertColors: true },
    { convertPathData: true },
    { convertShapeToPath: true },
    { convertStyleToAttrs: true },
    { convertTransform: true },
    { mergePaths: true },
    { moveElemsAttrsToGroup: true },
    { moveGroupAttrsToElems: true },
    { removeAttrs: { attrs: '(stroke|fill)' } },
    { removeComments: true },
    { removeDesc: true },
    { removeDimensions: true },
    { removeEditorsNSData: true },
    { removeEmptyAttrs: true },
    { removeEmptyContainers: true },
    { removeEmptyText: true },
    { removeHiddenElems: true },
    { removeMetadata: true },
    { removeNonInheritableGroupAttrs: true },
    { removeRasterImages: false },
    { removeTitle: true },
    { removeUnknownsAndDefaults: true },
    { removeUnusedNS: true },
    { removeUselessStrokeAndFill: true },
    { removeViewBox: false },
    { removeXMLProcInst: true },
    { sortAttrs: true },
    { transformsWithOnePath: false },
  ],
}

export default svgOptions
